### ISSUE TITLE
Support for "internal" backup procedure templates

### ISSUE THREAD

**Issue by blackandred** [riotkit-org/backup-maker-operator#11]
Backup Maker itself is providing templates internally, thus we do not need to provide them as cluster template, it's a twice work.
There should be a type "internal" to let the users use Backup Maker's templates, and alternatively to use their own templates if the type is set to "ClusterBackupProcedureTemplate".

**ClusterBackupProcedureTemplate example:**
```yaml
# ...
    templateRef:
        kind: ClusterBackupProcedureTemplate
        name: pg13
# ...
```

**"internal" example:**
```yaml
# ...
    templateRef:
        kind: internal
        name: wordpress
# ...
```
