### ISSUE TITLE
RequestedBackupAction as a trigger

### ISSUE THREAD

**Issue by blackandred** [riotkit-org/backup-maker-operator#3]
In order to be able to trigger an action we will use a resource type `RequestedBackupAction`

### Example

```yaml
---
apiVersion: riotkit.org/v1alpha1
kind: RequestedBackupAction
metadata:
    name: restore-to-v1
    namespace: default
spec:
    action: backup
    scheduledBackupRef:
        name: app1
    #targetVersion: v1
```
