### ISSUE TITLE
Automatically fill up helm values in "vars" section

### ISSUE THREAD

**Issue by blackandred** [riotkit-org/backup-maker-operator#30]
Assuming we already have information in our CRD we can pass it to the Helm Values.

**Example:**
```
spec:
    # (...)
    collectionId: some-name
    gpgKeySecretRef:
        email: example@example.org

    vars: |
        # (...)
        Repository:
          url: "http://my-example.org"
          token: "xxxxxx-yyyy-zzzz" # Is ignored and overwritten if using .spec.tokenSecretRef
          passphrase: "riotkit"

          # NOTICE: those two are duplicated, values from .spec.collectionId and .spec.gpgKeySecretRef.email can be inserted there
          recipient: "example@riseup.net"
          collectionId: some-name
```
